---
title: "Harvard Spring Course Enrollment Change"
author: "Neil Khurana"
date: "April 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(readr)
library(janitor)
library(reshape2)
```


```{r course_enrollment, echo = FALSE}

#The Harvard 2019 spring term data has been read and filtered for only the variables we are looking for. course_id, course_title and u_grad
#All NAs are removed

x_2019 <- read_excel("class_enrollment_summary_by_term_3.22.19.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(! is.na(course_name)) %>% 
  select(course_id, course_title, course_name, u_grad)

#The Harvard 2018 spring term data has been read and filtered for only the variables we are looking for. course_id, course_title and u_grad
#All NAs are removed


y_2018 <- read_xlsx("class_enrollment_summary_by_term_03.06.18.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(! is.na(course_name)) %>% 
  select(course_id, course_title, course_name, u_grad)
```

```{r join, echo = FALSE}
#We now join the two data sets together by using an inner join referencing course_id. Only the courses with with similiar id are included in this new data frame

z_joined <- inner_join(x_2019, y_2018, by = "course_id") %>% 
  
  #Course titles are the same for both, we only need to select one of the course title names
  
  select(course_title.x, course_name.x, u_grad.y, u_grad.x) %>% 
  
  #Here we may calculate the change of enrollemnt in the course from Spring 2018 to Spring 2019
  
  mutate(change = u_grad.x - u_grad.y) %>%
  
  #This takes the absolute value of the change of the class
  mutate(magnitude = abs(change)) %>% 
  
  #This arranged by desc magnitude. We don't care whether the class size increased or decreased, we just want the classes that changed size the most in either direction
  
  arrange(desc(magnitude)) %>% 
  
  #Only the top 10 classes will be used for our graph
  
  slice(1:5) %>% 
  select(-change, -magnitude, -course_name.x) %>% 
  melt(id.vars='course_title.x') 
```


```{r final_plot, echo = FALSE}
z_graphic <- z_joined %>% 
  ggplot(aes(fill = variable, y= value, x=course_title.x)) + 
    geom_bar(position="dodge", stat="identity") +
    labs(title = "Courses at Harvard with Greatest Change In Enrollment", 
         caption = "Source: Harvard Registrar",
         x = "Course Title",
         y = "Number of Undergraduates Enrolled",
         subtitle = "Diferences between Spring Semester of 2018 & 2019",
         fill = "Spring Semester") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) +
  scale_fill_discrete(name = "Spring Semester", labels = c("Spring 2018", "Spring 2019"))
z_graphic
```